location: southeastasia 
name: clamblob-scanner
resourceGroup: rg-clamblob 
type: Microsoft.App/containerApps 
properties:
  environmentId: /subscriptions/c9061bc7-fa28-41d9-a783-2600b29c6e2f/resourceGroups/rg-clamblob/providers/Microsoft.App/managedEnvironments/cae-common
  configuration:
    replicaTimeout: 10
    replicaRetryLimit: 10
    manualTriggerConfig:
      replicaCompletionCount: 1
      parallelism: 4
    triggerType: Manual
    initContainers: null
    scale:
      maxReplicas: 2
      minReplicas: 1
  template:
    containers:
    - image: wxzd/clamblob:v0.1.0
      name: clamblob-scanner
      resources: 
        cpu: 1.0
        memory: 2.0Gi 
      volumeMounts:
      - mountPath: "/mnt"
        volumeName: clamblob-scan
    environmentVariables:
    - name: MOUNT_PATH
      value: "/mnt"
    - name: APP_INSIGHTS_INSTRUMENTATION_KEY
      value: "5bb85efc-b516-4116-aebb-65ca9dcd876f"
    - name: CLAMAV_HOST
      value: "clamblob-clamav.purplestone-6b6c9ac6.southeastasia.azurecontainerapps.io"
    - name: CLAMAV_PORT
      value: 3310
    - QUARANTINE_CONTAINER_NAME:
      value: "quarantine"
    volumes:
    - name: clamblob-scan
      storageType: AzureFile
      storageName: clamblob-scan
  